# Generated by Django 3.1.7 on 2021-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productImage/')),
            ],
        ),
    ]
